<?php
namespace Overblog\ThriftBundle\Model\Comment;

/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT'].'/packages/Comment/Types.php';

$GLOBALS['Overblog_ThriftBundle_Model_Comment_Comment_CONSTANTS'] = array();

$GLOBALS['Overblog_ThriftBundle_Model_Comment_Comment_CONSTANTS']['hex_const'] = 31;

$GLOBALS['Overblog_ThriftBundle_Model_Comment_Comment_CONSTANTS']['GEN_ME'] = -3523553;

$GLOBALS['Overblog_ThriftBundle_Model_Comment_Comment_CONSTANTS']['GEn_DUB'] = 325.532;

$GLOBALS['Overblog_ThriftBundle_Model_Comment_Comment_CONSTANTS']['GEn_DU'] = 85.2355;

$GLOBALS['Overblog_ThriftBundle_Model_Comment_Comment_CONSTANTS']['GEN_STRING'] = "asldkjasfd";

$GLOBALS['Overblog_ThriftBundle_Model_Comment_Comment_CONSTANTS']['GEN_MAP'] = array(
  35532 => 233,
  43523 => 853,
);

$GLOBALS['Overblog_ThriftBundle_Model_Comment_Comment_CONSTANTS']['GEN_LIST'] = array(
  235235,
  23598352,
  3253523,
);


